name:
  Cron Job

on:
  schedule:
    - cron: "14 3 * * *"
 
jobs:
  cron:
    runs-on: ubuntu-latest
 
    steps:
      - name: Restart service
        run: >-
          curl --request POST \
            --url https://api.render.com/v1/services/${{ secrets.SERVICEID }}/restart \
            --header 'accept: application/json' \
            --header 'authorization: Bearer ${{ secrets.BEARER }}'
